import Head from "next/head";
import { useState, useEffect, useContext } from "react";
import { admin } from "../lib/whitelist";
import AccountSwitcher from "../components/AccountSwitcher";
import Lands from "../components/Lands";
import Summary from "../components/Summary";
import { UserContext } from "../lib/context";
import { getUserAccounts, getUserLands } from "../lib/hooks";
import { CommonCollection, Land, Plant } from "../lib/interface";
import AuthCheck from "../components/AuthCheck";

export default function Home() {
  const { user } = useContext(UserContext);
  const [accounts, loading, firstAccount] = getUserAccounts(user);
  const [selectedAccount, setSelectedAccount] = useState("");
  const [lands, plants]: [
    CommonCollection<Land>,
    CommonCollection<Plant>
  ] = getUserLands(user);

  useEffect(() => {
    if (!!firstAccount) {
      setSelectedAccount(firstAccount);
    }
  }, [firstAccount]);

  return (
    !loading && (
      <div className="p-4">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AuthCheck>
          <div className="container mx-auto">
            <br />
            {admin.includes(user?.email) && <Summary />}
            {admin.includes(user?.email) && (
              <AccountSwitcher
                accounts={accounts && Object.values(accounts)}
                setSelectedAccount={setSelectedAccount}
                selectedAccount={selectedAccount}
              />
            )}
            <Lands lands={lands} plants={plants} user={user} />
          </div>
        </AuthCheck>
      </div>
    )
  );
}
